spring.application.name=ebanking-chatbot

server.port=8086
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.3
spring.ai.openai.embedding.options.model=text-embedding-ada-002

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}

banking.api.base-url=http://localhost:8085/api
banking.api.username=admin
banking.api.password=1234